inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - lib/systemrdl/parser/generated_parser.rb
    - test/**/*
  NewCops: enable
  SuggestExtensions: false

Layout/EndOfLine:
  EnforcedStyle: lf

Naming/VariableNumber:
  EnforcedStyle: snake_case
  CheckSymbols: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantRegexpArgument:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets
