# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "preprocessor.y".
#

require 'racc/parser.rb'
module SystemRDL
  module Parser
    module Preprocessor
      class GeneratedPreprocessor < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    67,    68,    70,    71,    75,    64,    66,    69,    65,    76,
    24,    25,    26,    27,    77,    78,    23,    16,    17,    18,
    19,    20,    21,    22,    28,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    67,
    68,    79,    80,    81,    64,    66,    69,    65,    95,    24,
    25,    26,    27,   114,   118,    23,    16,    17,    18,    19,
    20,    21,    22,    28,    29,    30,    31,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    41,    42,    43,    44,
    45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
    55,    56,    57,    58,    59,    60,    61,    62,    82,    83,
    84,    85,    86,    87,   119,    88,    94,   120,    24,    25,
    26,    27,   133,   133,    23,    16,    17,    18,    19,    20,
    21,    22,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    82,    83,    84,
    85,    86,    87,   114,    88,   106,   137,    24,    25,    26,
    27,   138,   139,   107,   109,   120,   108,    96,   110,   145,
   146,    28,    29,    30,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    41,    42,    43,    44,    45,    46,
    47,    48,    49,    50,    51,    52,    53,    54,    55,    56,
    57,    58,    59,    60,    61,    62,    67,    68,   147,   133,
   151,    64,    66,    69,    65,   152,    24,    25,    26,    27,
   151,   154,    23,    16,    17,    18,    19,    20,    21,    22,
    28,    29,    30,    31,    32,    33,    34,    35,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    45,    46,    47,
    48,    49,    50,    51,    52,    53,    54,    55,    56,    57,
    58,    59,    60,    61,    62,    67,    68,   139,   156,   159,
    64,    66,    69,    65,   nil,    24,    25,    26,    27,   nil,
   nil,    23,    16,    17,    18,    19,    20,    21,    22,    28,
    29,    30,    31,    32,    33,    34,    35,    36,    37,    38,
    39,    40,    41,    42,    43,    44,    45,    46,    47,    48,
    49,    50,    51,    52,    53,    54,    55,    56,    57,    58,
    59,    60,    61,    62,    82,    83,    84,    85,    86,    87,
   nil,    88,    94,   nil,    24,    25,    26,    27,   nil,   nil,
    23,    16,    17,    18,    19,    20,    21,    22,    28,    29,
    30,    31,    32,    33,    34,    35,    36,    37,    38,    39,
    40,    41,    42,    43,    44,    45,    46,    47,    48,    49,
    50,    51,    52,    53,    54,    55,    56,    57,    58,    59,
    60,    61,    62,    82,    83,    84,    85,    86,    87,   nil,
    88,   106,   nil,    24,    25,    26,    27,   nil,   nil,   107,
   109,   nil,   108,   nil,   110,   nil,   nil,    28,    29,    30,
    31,    32,    33,    34,    35,    36,    37,    38,    39,    40,
    41,    42,    43,    44,    45,    46,    47,    48,    49,    50,
    51,    52,    53,    54,    55,    56,    57,    58,    59,    60,
    61,    62,    82,    83,    84,    85,    86,    87,   nil,    88,
   106,   nil,    24,    25,    26,    27,   nil,   nil,   107,   109,
   nil,   108,   nil,   110,   nil,   126,    28,    29,    30,    31,
    32,    33,    34,    35,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    45,    46,    47,    48,    49,    50,    51,
    52,    53,    54,    55,    56,    57,    58,    59,    60,    61,
    62,    82,    83,    84,    85,    86,    87,   nil,    88,   106,
   nil,    24,    25,    26,    27,   nil,   nil,   107,   109,   nil,
   108,   nil,   110,   nil,   126,    28,    29,    30,    31,    32,
    33,    34,    35,    36,    37,    38,    39,    40,    41,    42,
    43,    44,    45,    46,    47,    48,    49,    50,    51,    52,
    53,    54,    55,    56,    57,    58,    59,    60,    61,    62,
    82,    83,    84,    85,    86,    87,   nil,    88,   106,   nil,
    24,    25,    26,    27,   nil,   nil,   107,   109,   nil,   108,
   nil,   110,   nil,   126,    28,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    82,
    83,    84,    85,    86,    87,   nil,    88,    94,   nil,    24,
    25,    26,    27,   nil,   nil,    23,    16,    17,    18,    19,
    20,    21,    22,    28,    29,    30,    31,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    41,    42,    43,    44,
    45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
    55,    56,    57,    58,    59,    60,    61,    62,    82,    83,
    84,    85,    86,    87,   nil,    88,   106,   nil,    24,    25,
    26,    27,   nil,   nil,   107,   109,   nil,   108,   nil,   110,
   nil,   nil,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    82,    83,    84,
    85,    86,    87,   nil,    88,   106,   nil,    24,    25,    26,
    27,   nil,   nil,   107,   109,   nil,   108,   nil,   110,   nil,
   126,    28,    29,    30,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    41,    42,    43,    44,    45,    46,
    47,    48,    49,    50,    51,    52,    53,    54,    55,    56,
    57,    58,    59,    60,    61,    62,    67,    68,   nil,   nil,
   nil,    64,    66,    69,    65,   nil,    24,    25,    26,    27,
   nil,   nil,    23,    16,    17,    18,    19,    20,    21,    22,
    28,    29,    30,    31,    32,    33,    34,    35,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    45,    46,    47,
    48,    49,    50,    51,    52,    53,    54,    55,    56,    57,
    58,    59,    60,    61,    62,    67,    68,   nil,   nil,   nil,
    64,    66,    69,    65,   nil,    24,    25,    26,    27,   nil,
   nil,    23,    16,    17,    18,    19,    20,    21,    22,    28,
    29,    30,    31,    32,    33,    34,    35,    36,    37,    38,
    39,    40,    41,    42,    43,    44,    45,    46,    47,    48,
    49,    50,    51,    52,    53,    54,    55,    56,    57,    58,
    59,    60,    61,    62,    24,    25,    26,    27,   nil,   nil,
    23,    16,    17,    18,    19,    20,    21,    22,    28,    29,
    30,    31,    32,    33,    34,    35,    36,    37,    38,    39,
    40,    41,    42,    43,    44,    45,    46,    47,    48,    49,
    50,    51,    52,    53,    54,    55,    56,    57,    58,    59,
    60,    61,    62 ]

racc_action_check = [
     0,     0,     1,     2,    63,     0,     0,     0,     0,    65,
     0,     0,     0,     0,    66,    67,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     3,
     3,    68,    69,    70,     3,     3,     3,     3,    75,     3,
     3,     3,     3,    91,    95,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,    74,    74,
    74,    74,    74,    74,    97,    74,    74,    98,    74,    74,
    74,    74,   111,   112,    74,    74,    74,    74,    74,    74,
    74,    74,    74,    74,    74,    74,    74,    74,    74,    74,
    74,    74,    74,    74,    74,    74,    74,    74,    74,    74,
    74,    74,    74,    74,    74,    74,    74,    74,    74,    74,
    74,    74,    74,    74,    74,    74,    74,    76,    76,    76,
    76,    76,    76,   115,    76,    76,   116,    76,    76,    76,
    76,   117,   118,    76,    76,   121,    76,    76,    76,   128,
   129,    76,    76,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    76,    76,    76,    78,    78,   130,   131,
   132,    78,    78,    78,    78,   133,    78,    78,    78,    78,
   134,   139,    78,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    79,    79,   140,   150,   153,
    79,    79,    79,    79,   nil,    79,    79,    79,    79,   nil,
   nil,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    90,    90,    90,    90,    90,    90,
   nil,    90,    90,   nil,    90,    90,    90,    90,   nil,   nil,
    90,    90,    90,    90,    90,    90,    90,    90,    90,    90,
    90,    90,    90,    90,    90,    90,    90,    90,    90,    90,
    90,    90,    90,    90,    90,    90,    90,    90,    90,    90,
    90,    90,    90,    90,    90,    90,    90,    90,    90,    90,
    90,    90,    90,   101,   101,   101,   101,   101,   101,   nil,
   101,   101,   nil,   101,   101,   101,   101,   nil,   nil,   101,
   101,   nil,   101,   nil,   101,   nil,   nil,   101,   101,   101,
   101,   101,   101,   101,   101,   101,   101,   101,   101,   101,
   101,   101,   101,   101,   101,   101,   101,   101,   101,   101,
   101,   101,   101,   101,   101,   101,   101,   101,   101,   101,
   101,   101,   108,   108,   108,   108,   108,   108,   nil,   108,
   108,   nil,   108,   108,   108,   108,   nil,   nil,   108,   108,
   nil,   108,   nil,   108,   nil,   108,   108,   108,   108,   108,
   108,   108,   108,   108,   108,   108,   108,   108,   108,   108,
   108,   108,   108,   108,   108,   108,   108,   108,   108,   108,
   108,   108,   108,   108,   108,   108,   108,   108,   108,   108,
   108,   109,   109,   109,   109,   109,   109,   nil,   109,   109,
   nil,   109,   109,   109,   109,   nil,   nil,   109,   109,   nil,
   109,   nil,   109,   nil,   109,   109,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   109,   109,
   110,   110,   110,   110,   110,   110,   nil,   110,   110,   nil,
   110,   110,   110,   110,   nil,   nil,   110,   110,   nil,   110,
   nil,   110,   nil,   110,   110,   110,   110,   110,   110,   110,
   110,   110,   110,   110,   110,   110,   110,   110,   110,   110,
   110,   110,   110,   110,   110,   110,   110,   110,   110,   110,
   110,   110,   110,   110,   110,   110,   110,   110,   110,   114,
   114,   114,   114,   114,   114,   nil,   114,   114,   nil,   114,
   114,   114,   114,   nil,   nil,   114,   114,   114,   114,   114,
   114,   114,   114,   114,   114,   114,   114,   114,   114,   114,
   114,   114,   114,   114,   114,   114,   114,   114,   114,   114,
   114,   114,   114,   114,   114,   114,   114,   114,   114,   114,
   114,   114,   114,   114,   114,   114,   114,   114,   120,   120,
   120,   120,   120,   120,   nil,   120,   120,   nil,   120,   120,
   120,   120,   nil,   nil,   120,   120,   nil,   120,   nil,   120,
   nil,   nil,   120,   120,   120,   120,   120,   120,   120,   120,
   120,   120,   120,   120,   120,   120,   120,   120,   120,   120,
   120,   120,   120,   120,   120,   120,   120,   120,   120,   120,
   120,   120,   120,   120,   120,   120,   120,   127,   127,   127,
   127,   127,   127,   nil,   127,   127,   nil,   127,   127,   127,
   127,   nil,   nil,   127,   127,   nil,   127,   nil,   127,   nil,
   127,   127,   127,   127,   127,   127,   127,   127,   127,   127,
   127,   127,   127,   127,   127,   127,   127,   127,   127,   127,
   127,   127,   127,   127,   127,   127,   127,   127,   127,   127,
   127,   127,   127,   127,   127,   127,   151,   151,   nil,   nil,
   nil,   151,   151,   151,   151,   nil,   151,   151,   151,   151,
   nil,   nil,   151,   151,   151,   151,   151,   151,   151,   151,
   151,   151,   151,   151,   151,   151,   151,   151,   151,   151,
   151,   151,   151,   151,   151,   151,   151,   151,   151,   151,
   151,   151,   151,   151,   151,   151,   151,   151,   151,   151,
   151,   151,   151,   151,   151,   152,   152,   nil,   nil,   nil,
   152,   152,   152,   152,   nil,   152,   152,   152,   152,   nil,
   nil,   152,   152,   152,   152,   152,   152,   152,   152,   152,
   152,   152,   152,   152,   152,   152,   152,   152,   152,   152,
   152,   152,   152,   152,   152,   152,   152,   152,   152,   152,
   152,   152,   152,   152,   152,   152,   152,   152,   152,   152,
   152,   152,   152,   152,    12,    12,    12,    12,   nil,   nil,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12 ]

racc_action_pointer = [
    -2,     2,   -14,    57,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   932,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   -11,   nil,   -12,    -1,     0,    46,    50,
    63,   nil,   nil,   nil,   116,    47,   175,   nil,   234,   293,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   352,    62,   nil,   nil,   nil,    59,   nil,   102,   102,   nil,
   nil,   411,   nil,   nil,   nil,   nil,   nil,   nil,   470,   529,
   588,   128,   129,   nil,   647,   172,   170,   169,   167,   nil,
   706,   170,   nil,   nil,   nil,   nil,   nil,   765,   177,   180,
   214,   235,   235,   230,   245,   nil,   nil,   nil,   nil,   236,
   272,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   292,   824,   883,   293,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
  -123,  -123,  -123,    -2,    -4,    -5,    -6,    -7,    -8,    -9,
   -10,   -11,   -12,   -14,   -15,   -16,   -17,   -18,   -19,   -20,
   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,   -29,   -30,
   -31,   -32,   -33,   -34,   -35,   -36,   -37,   -38,   -39,   -40,
   -41,   -42,   -43,   -44,   -45,   -46,   -47,   -48,   -49,   -50,
   -51,   -52,   -53,   -54,   -55,   -56,   -57,   -58,   -59,   -60,
   -61,   -62,   -63,  -123,   -72,   -88,  -123,  -123,  -123,  -123,
  -123,    -1,    -3,   -13,   -79,   -74,  -123,  -113,  -123,  -123,
  -122,   160,   -64,   -65,   -66,   -67,   -68,   -69,   -70,   -71,
   -79,   -82,   -85,   -86,   -87,  -123,   -89,  -123,   -92,   -95,
   -96,   -97,   -99,  -100,  -101,  -102,  -103,  -104,  -108,  -108,
  -108,  -114,  -114,   -80,   -79,   -82,  -123,  -123,   -76,   -90,
  -123,   -92,   -94,   -98,  -105,  -106,  -107,  -108,  -123,  -123,
  -123,  -114,  -116,  -123,  -116,   -81,   -83,   -84,   -73,  -123,
   -76,   -78,   -91,   -93,  -109,  -110,  -111,  -112,  -115,  -117,
  -123,  -123,  -123,  -123,   -75,   -77,  -118,  -121,  -120,  -119 ]

racc_goto_table = [
     2,   103,    98,    99,   104,   100,   150,   116,   153,     1,
    72,    92,    73,    74,    89,   117,    93,   122,    97,   141,
   123,   nil,   nil,    91,   132,   134,   103,    92,    99,   104,
   100,   136,    93,   103,   103,   103,   104,   104,   104,   113,
   143,   155,   nil,   nil,   148,   103,   142,    99,   104,   100,
   nil,    92,   103,   nil,   nil,   104,    93,   128,   129,   130,
   nil,   nil,   nil,   135,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   144,   nil,   111,   112,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   157,   158 ]

racc_goto_check = [
     2,    14,    28,    31,    15,    32,    40,    26,    40,     1,
     4,    12,    13,    18,    19,    20,    16,    30,    27,    22,
    34,   nil,   nil,    24,    39,    39,    14,    12,    31,    15,
    32,    26,    16,    14,    14,    14,    15,    15,    15,    24,
    30,    22,   nil,   nil,    39,    14,    28,    31,    15,    32,
   nil,    12,    14,   nil,   nil,    15,    16,    36,    36,    36,
   nil,   nil,   nil,    24,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    36,   nil,     2,     2,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     2,     2 ]

racc_goto_pointer = [
   nil,     9,     0,   nil,     7,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -63,     0,   -75,   -72,   -58,   nil,   -50,   -60,
   -80,   nil,   -99,   nil,   -51,   nil,   -84,   -58,   -74,   nil,
   -81,   -73,   -71,   nil,   -81,   nil,   -51,   nil,   nil,   -87,
  -126 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,   105,    63,   nil,   nil,
   nil,   140,   nil,    90,   nil,   115,   nil,   nil,   nil,   121,
   nil,   124,   125,   101,   102,   127,   nil,   131,   149,   nil,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 63, :_reduce_1,
  1, 66, :_reduce_2,
  2, 66, :_reduce_3,
  1, 64, :_reduce_4,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 75, :_reduce_12,
  2, 75, :_reduce_13,
  1, 67, :_reduce_14,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  3, 68, :_reduce_71,
  1, 79, :_reduce_72,
  4, 80, :_reduce_73,
  1, 80, :_reduce_74,
  2, 83, :_reduce_75,
  0, 84, :_reduce_76,
  2, 84, :_reduce_77,
  2, 82, :_reduce_78,
  0, 86, :_reduce_79,
  2, 86, :_reduce_80,
  2, 87, :_reduce_81,
  0, 88, :_reduce_82,
  2, 88, :_reduce_83,
  3, 81, :_reduce_84,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 69, :_reduce_88,
  3, 69, :_reduce_89,
  4, 69, :_reduce_90,
  2, 91, :_reduce_91,
  0, 92, :_reduce_92,
  2, 92, :_reduce_93,
  2, 89, :_reduce_94,
  1, 95, :_reduce_95,
  1, 95, :_reduce_96,
  1, 96, :_reduce_97,
  2, 96, :_reduce_98,
  1, 90, :_reduce_99,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 97, :_reduce_105,
  1, 97, :_reduce_106,
  1, 97, :_reduce_107,
  0, 98, :_reduce_108,
  2, 98, :_reduce_109,
  3, 94, :_reduce_110,
  3, 94, :_reduce_111,
  3, 94, :_reduce_112,
  2, 70, :_reduce_113,
  0, 101, :_reduce_114,
  2, 101, :_reduce_115,
  0, 102, :_reduce_none,
  1, 102, :_reduce_none,
  6, 71, :_reduce_118,
  6, 72, :_reduce_119,
  3, 99, :_reduce_120,
  2, 100, :_reduce_121,
  2, 73, :_reduce_122 ]

racc_reduce_n = 123

racc_shift_n = 160

racc_token_table = {
  false => 0,
  :error => 1,
  :PP_IFDEF => 2,
  :PP_IFNDEF => 3,
  :PP_ELSIF => 4,
  :PP_ELSE => 5,
  :PP_ENDIF => 6,
  :PP_DEFINE => 7,
  :PP_UNDEF => 8,
  :PP_INCLUDE => 9,
  :PP_MACRO_ID => 10,
  :PP_NL => 11,
  :STRING => 12,
  :NUMBER => 13,
  :VERILOG_NUMBER => 14,
  :SIMPLE_ID => 15,
  :NL => 16,
  :EOS => 17,
  :ILLEGAL_CHARACTER => 18,
  "[" => 19,
  "]" => 20,
  "(" => 21,
  ")" => 22,
  "{" => 23,
  "}" => 24,
  "," => 25,
  "!" => 26,
  "&&" => 27,
  "||" => 28,
  "<" => 29,
  ">" => 30,
  "<=" => 31,
  ">=" => 32,
  "==" => 33,
  "!=" => 34,
  ">>" => 35,
  "<<" => 36,
  "~" => 37,
  "&" => 38,
  "~&" => 39,
  "|" => 40,
  "~|" => 41,
  "^" => 42,
  "~^" => 43,
  "^~" => 44,
  "*" => 45,
  "/" => 46,
  "%" => 47,
  "+" => 48,
  "-" => 49,
  "**" => 50,
  "?" => 51,
  ":" => 52,
  "->" => 53,
  "." => 54,
  "'" => 55,
  ";" => 56,
  "=" => 57,
  "@" => 58,
  "+=" => 59,
  "%=" => 60,
  "-temp-group" => 61 }

racc_nt_base = 62

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "PP_IFDEF",
  "PP_IFNDEF",
  "PP_ELSIF",
  "PP_ELSE",
  "PP_ENDIF",
  "PP_DEFINE",
  "PP_UNDEF",
  "PP_INCLUDE",
  "PP_MACRO_ID",
  "PP_NL",
  "STRING",
  "NUMBER",
  "VERILOG_NUMBER",
  "SIMPLE_ID",
  "NL",
  "EOS",
  "ILLEGAL_CHARACTER",
  "\"[\"",
  "\"]\"",
  "\"(\"",
  "\")\"",
  "\"{\"",
  "\"}\"",
  "\",\"",
  "\"!\"",
  "\"&&\"",
  "\"||\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"==\"",
  "\"!=\"",
  "\">>\"",
  "\"<<\"",
  "\"~\"",
  "\"&\"",
  "\"~&\"",
  "\"|\"",
  "\"~|\"",
  "\"^\"",
  "\"~^\"",
  "\"^~\"",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "\"**\"",
  "\"?\"",
  "\":\"",
  "\"->\"",
  "\".\"",
  "\"'\"",
  "\";\"",
  "\"=\"",
  "\"@\"",
  "\"+=\"",
  "\"%=\"",
  "\"-temp-group\"",
  "$start",
  "root",
  "source_description",
  "source_item",
  "\"-many1@source_item\"",
  "rdl_tokens",
  "text_macro_definition",
  "text_macro_usage",
  "undef",
  "ifdef",
  "ifndef",
  "include",
  "rdl_token",
  "\"-many1@rdl_token\"",
  "rdl_literal",
  "rdl_symbol",
  "pp_keyword",
  "text_macro_start",
  "text_macro_header",
  "text_macro_body",
  "text_macro_params",
  "\"-group@\\\",\\\"-SIMPLE_ID\"",
  "\"-many@-group@\\\",\\\"-SIMPLE_ID\"",
  "text_macro_token",
  "\"-many@text_macro_token\"",
  "\"-group@PP_NL-\\\"-many@text_macro_token\\\"\"",
  "\"-many@-group@PP_NL-\\\"-many@text_macro_token\\\"\"",
  "text_macro_args",
  "text_macro_arg",
  "\"-group@\\\",\\\"-text_macro_arg\"",
  "\"-many@-group@\\\",\\\"-text_macro_arg\"",
  "text_macro_simple_arg_element",
  "text_macro_bracketed_arg_group",
  "\"-group@text_macro_simple_arg_element|text_macro_bracketed_arg_group\"",
  "\"-many1@-group@text_macro_simple_arg_element|text_macro_bracketed_arg_group\"",
  "\"-group@text_macro_simple_arg_element|text_macro_bracketed_arg_group|\\\",\\\"\"",
  "\"-many@-group@text_macro_simple_arg_element|text_macro_bracketed_arg_group|\\\",\\\"\"",
  "elsif",
  "else",
  "\"-many@elsif\"",
  "\"-option@else\"" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'preprocessor.y', 20)
  def _reduce_1(val, _values, result)
            result = Root.new(val[0], val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 30)
  def _reduce_2(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 30)
  def _reduce_3(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 25)
  def _reduce_4(val, _values, result)
            result = SourceDescription.new(val[0])

    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'preprocessor.y', 43)
  def _reduce_12(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 43)
  def _reduce_13(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 39)
  def _reduce_14(val, _values, result)
            result = RdlTokens.new(val[0])

    result
  end
.,.,

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

module_eval(<<'.,.,', 'preprocessor.y', 60)
  def _reduce_71(val, _values, result)
            result = Define.new(val[1][0], val[1][1], val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 64)
  def _reduce_72(val, _values, result)
            enter_macro_body
        result = val[0]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 69)
  def _reduce_73(val, _values, result)
            result = [val[0], val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 72)
  def _reduce_74(val, _values, result)
            result = [val[0]]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_75(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_76(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_77(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 76)
  def _reduce_78(val, _values, result)
            result = collect_list_items(val)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_79(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_80(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_81(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_82(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_83(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_84(val, _values, result)
            exit_macro_body
        result = val.flatten

    result
  end
.,.,

# reduce 85 omitted

# reduce 86 omitted

# reduce 87 omitted

module_eval(<<'.,.,', 'preprocessor.y', 91)
  def _reduce_88(val, _values, result)
            token_range = Utils.to_token_range(val)
        result = MacroUsage.new(val[0], nil, nil, nil, token_range)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 95)
  def _reduce_89(val, _values, result)
            token_range = Utils.to_token_range(val)
        result = MacroUsage.new(val[0], nil, val[1], val[2], token_range)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 99)
  def _reduce_90(val, _values, result)
            token_range = Utils.to_token_range(val)
        result = MacroUsage.new(val[0], val[2], nil, nil, token_range)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 108)
  def _reduce_91(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 108)
  def _reduce_92(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 108)
  def _reduce_93(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 104)
  def _reduce_94(val, _values, result)
            result = collect_list_items(val)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 112)
  def _reduce_95(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 112)
  def _reduce_96(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 112)
  def _reduce_97(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 112)
  def _reduce_98(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 108)
  def _reduce_99(val, _values, result)
            result = val[0].flatten

    result
  end
.,.,

# reduce 100 omitted

# reduce 101 omitted

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

module_eval(<<'.,.,', 'preprocessor.y', 128)
  def _reduce_105(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 128)
  def _reduce_106(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 128)
  def _reduce_107(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 128)
  def _reduce_108(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 128)
  def _reduce_109(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 114)
  def _reduce_110(val, _values, result)
            result = val.flatten

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 117)
  def _reduce_111(val, _values, result)
            result = val.flatten

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 120)
  def _reduce_112(val, _values, result)
            result = val.flatten

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 128)
  def _reduce_113(val, _values, result)
            result = Undef.new(val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 141)
  def _reduce_114(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 141)
  def _reduce_115(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 116 omitted

# reduce 117 omitted

module_eval(<<'.,.,', 'preprocessor.y', 136)
  def _reduce_118(val, _values, result)
            if_branch = [val[1], false, val[2]]
        result = Ifdef.new(if_branch, val[3], val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 141)
  def _reduce_119(val, _values, result)
          if_branch = [val[1], true, val[2]]
      result = Ifdef.new(if_branch, val[3], val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 146)
  def _reduce_120(val, _values, result)
            result = [val[1], false, val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 150)
  def _reduce_121(val, _values, result)
            result = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 158)
  def _reduce_122(val, _values, result)
            result = Include.new(val[1])

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

      end   # class GeneratedPreprocessor
    end   # module Preprocessor
  end   # module Parser
end   # module SystemRDL
