# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "preprocessor.y".
#

require 'racc/parser.rb'
module SystemRDL
  module Parser
    module Preprocessor
      class GeneratedPreprocessor < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
   125,   126,   127,   128,   131,   124,   132,    14,    15,    16,
    17,    18,    19,    20,    21,    22,    23,    24,    25,    26,
    27,    28,    29,    30,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    41,    42,    43,    44,    45,    46,
    47,    48,    49,    50,    51,    52,    53,    54,    55,    56,
    57,    58,    59,    60,    61,    62,    63,    64,    65,    66,
    67,    68,    69,    70,    71,    72,    73,    74,    75,    76,
    77,    78,    79,    80,    81,   133,    82,    83,    84,    85,
    86,    87,    88,    89,    90,    91,    92,    93,    94,    95,
    96,    97,    98,    99,   100,   101,   102,   103,   104,   105,
   106,   107,   108,   109,   110,   111,   112,   113,   114,   115,
   116,   117,   118,   119,   120,   121,   122,   123,   125,   126,
   134,   139,   139,   124,   139,    14,    15,    16,    17,    18,
    19,    20,    21,    22,    23,    24,    25,    26,    27,    28,
    29,    30,    31,    32,    33,    34,    35,    36,    37,    38,
    39,    40,    41,    42,    43,    44,    45,    46,    47,    48,
    49,    50,    51,    52,    53,    54,    55,    56,    57,    58,
    59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
    69,    70,    71,    72,    73,    74,    75,    76,    77,    78,
    79,    80,    81,   144,    82,    83,    84,    85,    86,    87,
    88,    89,    90,    91,    92,    93,    94,    95,    96,    97,
    98,    99,   100,   101,   102,   103,   104,   105,   106,   107,
   108,   109,   110,   111,   112,   113,   114,   115,   116,   117,
   118,   119,   120,   121,   122,   123,   125,   126,   145,   144,
   147,   124,   150,    14,    15,    16,    17,    18,    19,    20,
    21,    22,    23,    24,    25,    26,    27,    28,    29,    30,
    31,    32,    33,    34,    35,    36,    37,    38,    39,    40,
    41,    42,    43,    44,    45,    46,    47,    48,    49,    50,
    51,    52,    53,    54,    55,    56,    57,    58,    59,    60,
    61,    62,    63,    64,    65,    66,    67,    68,    69,    70,
    71,    72,    73,    74,    75,    76,    77,    78,    79,    80,
    81,   nil,    82,    83,    84,    85,    86,    87,    88,    89,
    90,    91,    92,    93,    94,    95,    96,    97,    98,    99,
   100,   101,   102,   103,   104,   105,   106,   107,   108,   109,
   110,   111,   112,   113,   114,   115,   116,   117,   118,   119,
   120,   121,   122,   123,   125,   126,   nil,   nil,   nil,   124,
   nil,    14,    15,    16,    17,    18,    19,    20,    21,    22,
    23,    24,    25,    26,    27,    28,    29,    30,    31,    32,
    33,    34,    35,    36,    37,    38,    39,    40,    41,    42,
    43,    44,    45,    46,    47,    48,    49,    50,    51,    52,
    53,    54,    55,    56,    57,    58,    59,    60,    61,    62,
    63,    64,    65,    66,    67,    68,    69,    70,    71,    72,
    73,    74,    75,    76,    77,    78,    79,    80,    81,   nil,
    82,    83,    84,    85,    86,    87,    88,    89,    90,    91,
    92,    93,    94,    95,    96,    97,    98,    99,   100,   101,
   102,   103,   104,   105,   106,   107,   108,   109,   110,   111,
   112,   113,   114,   115,   116,   117,   118,   119,   120,   121,
   122,   123,   125,   126,   nil,   nil,   nil,   124,   nil,    14,
    15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
    25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    41,    42,    43,    44,
    45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
    55,    56,    57,    58,    59,    60,    61,    62,    63,    64,
    65,    66,    67,    68,    69,    70,    71,    72,    73,    74,
    75,    76,    77,    78,    79,    80,    81,   nil,    82,    83,
    84,    85,    86,    87,    88,    89,    90,    91,    92,    93,
    94,    95,    96,    97,    98,    99,   100,   101,   102,   103,
   104,   105,   106,   107,   108,   109,   110,   111,   112,   113,
   114,   115,   116,   117,   118,   119,   120,   121,   122,   123,
   125,   126,   nil,   nil,   nil,   124,   nil,    14,    15,    16,
    17,    18,    19,    20,    21,    22,    23,    24,    25,    26,
    27,    28,    29,    30,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    41,    42,    43,    44,    45,    46,
    47,    48,    49,    50,    51,    52,    53,    54,    55,    56,
    57,    58,    59,    60,    61,    62,    63,    64,    65,    66,
    67,    68,    69,    70,    71,    72,    73,    74,    75,    76,
    77,    78,    79,    80,    81,   nil,    82,    83,    84,    85,
    86,    87,    88,    89,    90,    91,    92,    93,    94,    95,
    96,    97,    98,    99,   100,   101,   102,   103,   104,   105,
   106,   107,   108,   109,   110,   111,   112,   113,   114,   115,
   116,   117,   118,   119,   120,   121,   122,   123,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    66,    67,    68,    69,    70,    71,    72,    73,    74,    75,
    76,    77,    78,    79,    80,    81,   nil,    82,    83,    84,
    85,    86,    87,    88,    89,    90,    91,    92,    93,    94,
    95,    96,    97,    98,    99,   100,   101,   102,   103,   104,
   105,   106,   107,   108,   109,   110,   111,   112,   113,   114,
   115,   116,   117,   118,   119,   120,   121,   122,   123 ]

racc_action_check = [
     0,     0,     1,     2,   124,     0,   125,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,   126,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     3,     3,
   127,   135,   136,     3,   137,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,   138,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,   132,   132,   139,   140,
   143,   132,   146,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   nil,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   133,   133,   nil,   nil,   nil,   133,
   nil,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   nil,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   133,   133,   144,   144,   nil,   nil,   nil,   144,   nil,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   nil,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   145,   145,   nil,   nil,   nil,   145,   nil,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   nil,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,   nil,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9 ]

racc_action_pointer = [
    -2,     2,   -74,   116,   nil,   nil,   nil,   nil,   nil,   699,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -72,   -70,    -1,   120,   nil,   nil,
   nil,   nil,   234,   352,   nil,   117,   118,   120,   188,   162,
   234,   nil,   nil,   234,   470,   588,   236,   nil,   nil,   nil,
   nil ]

racc_action_default = [
  -134,  -134,  -134,    -2,    -4,    -5,    -6,    -7,    -8,    -9,
   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,
   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,   -29,   -30,
   -31,   -32,   -33,   -34,   -35,   -36,   -37,   -38,   -39,   -40,
   -41,   -42,   -43,   -44,   -45,   -46,   -47,   -48,   -49,   -50,
   -51,   -52,   -53,   -54,   -55,   -56,   -57,   -58,   -59,   -60,
   -61,   -62,   -63,   -64,   -65,   -66,   -67,   -68,   -69,   -70,
   -71,   -72,   -73,   -74,   -75,   -76,   -77,   -78,   -79,   -80,
   -81,   -82,   -83,   -84,   -85,   -86,   -87,   -88,   -89,   -90,
   -91,   -92,   -93,   -94,   -95,   -96,   -97,   -98,   -99,  -100,
  -101,  -102,  -103,  -104,  -105,  -106,  -107,  -108,  -109,  -110,
  -111,  -112,  -113,  -114,  -115,  -116,  -117,  -118,  -119,  -120,
  -121,  -122,  -123,  -124,  -134,  -134,  -134,  -134,    -1,    -3,
   -10,  -125,  -134,  -134,   151,  -126,  -126,  -126,  -128,  -134,
  -128,  -127,  -129,  -134,  -134,  -134,  -134,  -130,  -133,  -132,
  -131 ]

racc_goto_table = [
     2,   138,   140,   141,   143,     1,   146,   129,   130,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   135,   136,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   148,   149 ]

racc_goto_check = [
     2,    16,    16,    16,    17,     1,    17,     4,    10,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     2,     2,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     2,     2 ]

racc_goto_pointer = [
   nil,     5,     0,   nil,     4,   nil,   nil,   nil,   nil,   nil,
    -1,   nil,   nil,   nil,   nil,   nil,  -134,  -134 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,   137,   142,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 121, :_reduce_1,
  1, 124, :_reduce_2,
  2, 124, :_reduce_3,
  1, 122, :_reduce_4,
  1, 123, :_reduce_none,
  1, 123, :_reduce_none,
  1, 123, :_reduce_none,
  1, 123, :_reduce_none,
  1, 130, :_reduce_9,
  2, 130, :_reduce_10,
  1, 125, :_reduce_11,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 131, :_reduce_none,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  1, 132, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  2, 126, :_reduce_125,
  0, 136, :_reduce_126,
  2, 136, :_reduce_127,
  0, 137, :_reduce_none,
  1, 137, :_reduce_none,
  6, 127, :_reduce_130,
  6, 128, :_reduce_131,
  3, 134, :_reduce_132,
  2, 135, :_reduce_133 ]

racc_reduce_n = 134

racc_shift_n = 151

racc_token_table = {
  false => 0,
  :error => 1,
  :PP_IFDEF => 2,
  :PP_IFNDEF => 3,
  :PP_ELSIF => 4,
  :PP_ELSE => 5,
  :PP_ENDIF => 6,
  :PP_DEFINE => 7,
  :PP_MACRO_ID => 8,
  :KW_ABSTRACT => 9,
  :KW_ACCESSTYPE => 10,
  :KW_ADDRESSINGTYPE => 11,
  :KW_ADDRMAP => 12,
  :KW_ALIAS => 13,
  :KW_ALL => 14,
  :KW_BIT => 15,
  :KW_BOOLEAN => 16,
  :KW_BOTHEDGE => 17,
  :KW_COMPACT => 18,
  :KW_COMPONENT => 19,
  :KW_COMPONENTWIDTH => 20,
  :KW_CONSTRAINT => 21,
  :KW_DEFAULT => 22,
  :KW_ENCODE => 23,
  :KW_ENUM => 24,
  :KW_EXTERNAL => 25,
  :KW_FALSE => 26,
  :KW_FIELD => 27,
  :KW_FULLALIGN => 28,
  :KW_HW => 29,
  :KW_INSIDE => 30,
  :KW_INTERNAL => 31,
  :KW_LEVEL => 32,
  :KW_LONGINT => 33,
  :KW_MEM => 34,
  :KW_NA => 35,
  :KW_NEGEDGE => 36,
  :KW_NONSTICKY => 37,
  :KW_NUMBER => 38,
  :KW_ONREADTYPE => 39,
  :KW_ONWRITETYPE => 40,
  :KW_POSEDGE => 41,
  :KW_PROPERTY => 42,
  :KW_R => 43,
  :KW_RCLR => 44,
  :KW_REF => 45,
  :KW_REG => 46,
  :KW_REGALIGN => 47,
  :KW_REGFILE => 48,
  :KW_RSET => 49,
  :KW_RUSER => 50,
  :KW_RW => 51,
  :KW_RW1 => 52,
  :KW_SIGNAL => 53,
  :KW_STRING => 54,
  :KW_STRUCT => 55,
  :KW_SW => 56,
  :KW_THIS => 57,
  :KW_TRUE => 58,
  :KW_TYPE => 59,
  :KW_UNSIGNED => 60,
  :KW_W => 61,
  :KW_W1 => 62,
  :KW_WCLR => 63,
  :KW_WOCLR => 64,
  :KW_WOSET => 65,
  :KW_WOT => 66,
  :KW_WR => 67,
  :KW_WSET => 68,
  :KW_WUSER => 69,
  :KW_WZC => 70,
  :KW_WZS => 71,
  :KW_WZT => 72,
  :STRING => 73,
  :NUMBER => 74,
  :VERILOG_NUMBER => 75,
  :SIMPLE_ID => 76,
  :EOS => 77,
  "[" => 78,
  "]" => 79,
  "(" => 80,
  ")" => 81,
  "{" => 82,
  "}" => 83,
  "!" => 84,
  "&&" => 85,
  "||" => 86,
  "<" => 87,
  ">" => 88,
  "<=" => 89,
  ">=" => 90,
  "==" => 91,
  "!=" => 92,
  ">>" => 93,
  "<<" => 94,
  "~" => 95,
  "&" => 96,
  "~&" => 97,
  "|" => 98,
  "~|" => 99,
  "^" => 100,
  "~^" => 101,
  "^~" => 102,
  "*" => 103,
  "/" => 104,
  "%" => 105,
  "+" => 106,
  "-" => 107,
  "**" => 108,
  "?" => 109,
  ":" => 110,
  "->" => 111,
  "." => 112,
  "," => 113,
  "'" => 114,
  ";" => 115,
  "=" => 116,
  "@" => 117,
  "+=" => 118,
  "%=" => 119 }

racc_nt_base = 120

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "PP_IFDEF",
  "PP_IFNDEF",
  "PP_ELSIF",
  "PP_ELSE",
  "PP_ENDIF",
  "PP_DEFINE",
  "PP_MACRO_ID",
  "KW_ABSTRACT",
  "KW_ACCESSTYPE",
  "KW_ADDRESSINGTYPE",
  "KW_ADDRMAP",
  "KW_ALIAS",
  "KW_ALL",
  "KW_BIT",
  "KW_BOOLEAN",
  "KW_BOTHEDGE",
  "KW_COMPACT",
  "KW_COMPONENT",
  "KW_COMPONENTWIDTH",
  "KW_CONSTRAINT",
  "KW_DEFAULT",
  "KW_ENCODE",
  "KW_ENUM",
  "KW_EXTERNAL",
  "KW_FALSE",
  "KW_FIELD",
  "KW_FULLALIGN",
  "KW_HW",
  "KW_INSIDE",
  "KW_INTERNAL",
  "KW_LEVEL",
  "KW_LONGINT",
  "KW_MEM",
  "KW_NA",
  "KW_NEGEDGE",
  "KW_NONSTICKY",
  "KW_NUMBER",
  "KW_ONREADTYPE",
  "KW_ONWRITETYPE",
  "KW_POSEDGE",
  "KW_PROPERTY",
  "KW_R",
  "KW_RCLR",
  "KW_REF",
  "KW_REG",
  "KW_REGALIGN",
  "KW_REGFILE",
  "KW_RSET",
  "KW_RUSER",
  "KW_RW",
  "KW_RW1",
  "KW_SIGNAL",
  "KW_STRING",
  "KW_STRUCT",
  "KW_SW",
  "KW_THIS",
  "KW_TRUE",
  "KW_TYPE",
  "KW_UNSIGNED",
  "KW_W",
  "KW_W1",
  "KW_WCLR",
  "KW_WOCLR",
  "KW_WOSET",
  "KW_WOT",
  "KW_WR",
  "KW_WSET",
  "KW_WUSER",
  "KW_WZC",
  "KW_WZS",
  "KW_WZT",
  "STRING",
  "NUMBER",
  "VERILOG_NUMBER",
  "SIMPLE_ID",
  "EOS",
  "\"[\"",
  "\"]\"",
  "\"(\"",
  "\")\"",
  "\"{\"",
  "\"}\"",
  "\"!\"",
  "\"&&\"",
  "\"||\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"==\"",
  "\"!=\"",
  "\">>\"",
  "\"<<\"",
  "\"~\"",
  "\"&\"",
  "\"~&\"",
  "\"|\"",
  "\"~|\"",
  "\"^\"",
  "\"~^\"",
  "\"^~\"",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "\"**\"",
  "\"?\"",
  "\":\"",
  "\"->\"",
  "\".\"",
  "\",\"",
  "\"'\"",
  "\";\"",
  "\"=\"",
  "\"@\"",
  "\"+=\"",
  "\"%=\"",
  "$start",
  "root",
  "source_description",
  "source_item",
  "\"-many1@source_item\"",
  "rdl_tokens",
  "define",
  "ifdef",
  "ifndef",
  "rdl_token",
  "\"-many1@rdl_token\"",
  "rdl_keyword",
  "rdl_literal",
  "rdl_symbol",
  "elsif",
  "else",
  "\"-many@elsif\"",
  "\"-option@else\"" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'preprocessor.y', 31)
  def _reduce_1(val, _values, result)
            result = Root.new(val[0], val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 41)
  def _reduce_2(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 41)
  def _reduce_3(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 36)
  def _reduce_4(val, _values, result)
            result = SourceDescription.new(val[0])

    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

module_eval(<<'.,.,', 'preprocessor.y', 51)
  def _reduce_9(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 51)
  def _reduce_10(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 47)
  def _reduce_11(val, _values, result)
            result = RdlTokens.new(val[0])

    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

# reduce 85 omitted

# reduce 86 omitted

# reduce 87 omitted

# reduce 88 omitted

# reduce 89 omitted

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

# reduce 93 omitted

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

# reduce 97 omitted

# reduce 98 omitted

# reduce 99 omitted

# reduce 100 omitted

# reduce 101 omitted

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

# reduce 106 omitted

# reduce 107 omitted

# reduce 108 omitted

# reduce 109 omitted

# reduce 110 omitted

# reduce 111 omitted

# reduce 112 omitted

# reduce 113 omitted

# reduce 114 omitted

# reduce 115 omitted

# reduce 116 omitted

# reduce 117 omitted

# reduce 118 omitted

# reduce 119 omitted

# reduce 120 omitted

# reduce 121 omitted

# reduce 122 omitted

# reduce 123 omitted

# reduce 124 omitted

module_eval(<<'.,.,', 'preprocessor.y', 75)
  def _reduce_125(val, _values, result)
            result = Define.new(val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_126(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_127(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 128 omitted

# reduce 129 omitted

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_130(val, _values, result)
            if_branch = [val[1], false, val[2]]
        result = Ifdef.new(if_branch, val[3], val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_131(val, _values, result)
          if_branch = [val[1], true, val[2]]
      result = Ifdef.new(if_branch, val[3], val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 90)
  def _reduce_132(val, _values, result)
            result = [val[1], false, val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 94)
  def _reduce_133(val, _values, result)
            result = val[1]

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

      end   # class GeneratedPreprocessor
    end   # module Preprocessor
  end   # module Parser
end   # module SystemRDL
