# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "preprocessor.y".
#

require 'racc/parser.rb'
module SystemRDL
  module Parser
    module Preprocessor
      class GeneratedPreprocessor < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    68,    69,    71,    72,    76,    65,    67,    70,    66,    77,
    25,    26,    27,    28,    78,    79,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    68,    69,    80,    81,    82,    65,    67,    70,    66,    96,
    25,    26,    27,    28,   116,   120,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   121,    89,    95,   122,
    25,    26,    27,    28,   136,   136,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   116,    89,   107,   140,
    25,    26,    27,    28,   141,   142,   108,   111,   122,   109,
    97,   110,   112,   148,   149,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    68,    69,   150,   151,   136,    65,    67,    70,    66,   155,
    25,    26,    27,    28,   156,   155,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    68,    69,   158,   142,   160,    65,    67,    70,    66,   163,
    25,    26,    27,    28,   nil,   nil,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,    95,   nil,
    25,    26,    27,    28,   nil,   nil,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,   107,   nil,
    25,    26,    27,    28,   nil,   nil,   108,   111,   nil,   109,
   nil,   110,   112,   nil,   nil,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,   107,   nil,
    25,    26,    27,    28,   nil,   nil,   108,   111,   nil,   109,
   nil,   110,   112,   nil,   128,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,   107,   nil,
    25,    26,    27,    28,   nil,   nil,   108,   111,   nil,   109,
   nil,   110,   112,   nil,   128,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,   107,   nil,
    25,    26,    27,    28,   nil,   nil,   108,   111,   nil,   109,
   nil,   110,   112,   nil,   128,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,   107,   nil,
    25,    26,    27,    28,   nil,   nil,   108,   111,   nil,   109,
   nil,   110,   112,   nil,   128,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,    95,   nil,
    25,    26,    27,    28,   nil,   nil,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,   107,   nil,
    25,    26,    27,    28,   nil,   nil,   108,   111,   nil,   109,
   nil,   110,   112,   nil,   nil,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    83,    84,    85,    86,    87,    88,   nil,    89,   107,   nil,
    25,    26,    27,    28,   nil,   nil,   108,   111,   nil,   109,
   nil,   110,   112,   nil,   128,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    68,    69,   nil,   nil,   nil,    65,    67,    70,    66,   nil,
    25,    26,    27,    28,   nil,   nil,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    68,    69,   nil,   nil,   nil,    65,    67,    70,    66,   nil,
    25,    26,    27,    28,   nil,   nil,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    25,    26,    27,    28,   nil,   nil,    24,    16,    17,    18,
    19,    20,    21,    22,    23,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63 ]

racc_action_check = [
     0,     0,     1,     2,    64,     0,     0,     0,     0,    66,
     0,     0,     0,     0,    67,    68,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     3,     3,    69,    70,    71,     3,     3,     3,     3,    76,
     3,     3,     3,     3,    92,    96,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
    75,    75,    75,    75,    75,    75,    98,    75,    75,    99,
    75,    75,    75,    75,   113,   114,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    77,    77,    77,    77,    77,    77,   117,    77,    77,   118,
    77,    77,    77,    77,   119,   120,    77,    77,   123,    77,
    77,    77,    77,   130,   131,    77,    77,    77,    77,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
    79,    79,   132,   133,   134,    79,    79,    79,    79,   135,
    79,    79,    79,    79,   136,   137,    79,    79,    79,    79,
    79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    79,    79,    79,    79,    79,    79,    79,    79,    79,    79,
    80,    80,   142,   143,   154,    80,    80,    80,    80,   157,
    80,    80,    80,    80,   nil,   nil,    80,    80,    80,    80,
    80,    80,    80,    80,    80,    80,    80,    80,    80,    80,
    80,    80,    80,    80,    80,    80,    80,    80,    80,    80,
    80,    80,    80,    80,    80,    80,    80,    80,    80,    80,
    80,    80,    80,    80,    80,    80,    80,    80,    80,    80,
    91,    91,    91,    91,    91,    91,   nil,    91,    91,   nil,
    91,    91,    91,    91,   nil,   nil,    91,    91,    91,    91,
    91,    91,    91,    91,    91,    91,    91,    91,    91,    91,
    91,    91,    91,    91,    91,    91,    91,    91,    91,    91,
    91,    91,    91,    91,    91,    91,    91,    91,    91,    91,
    91,    91,    91,    91,    91,    91,    91,    91,    91,    91,
   102,   102,   102,   102,   102,   102,   nil,   102,   102,   nil,
   102,   102,   102,   102,   nil,   nil,   102,   102,   nil,   102,
   nil,   102,   102,   nil,   nil,   102,   102,   102,   102,   102,
   102,   102,   102,   102,   102,   102,   102,   102,   102,   102,
   102,   102,   102,   102,   102,   102,   102,   102,   102,   102,
   102,   102,   102,   102,   102,   102,   102,   102,   102,   102,
   109,   109,   109,   109,   109,   109,   nil,   109,   109,   nil,
   109,   109,   109,   109,   nil,   nil,   109,   109,   nil,   109,
   nil,   109,   109,   nil,   109,   109,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   109,   109,
   110,   110,   110,   110,   110,   110,   nil,   110,   110,   nil,
   110,   110,   110,   110,   nil,   nil,   110,   110,   nil,   110,
   nil,   110,   110,   nil,   110,   110,   110,   110,   110,   110,
   110,   110,   110,   110,   110,   110,   110,   110,   110,   110,
   110,   110,   110,   110,   110,   110,   110,   110,   110,   110,
   110,   110,   110,   110,   110,   110,   110,   110,   110,   110,
   111,   111,   111,   111,   111,   111,   nil,   111,   111,   nil,
   111,   111,   111,   111,   nil,   nil,   111,   111,   nil,   111,
   nil,   111,   111,   nil,   111,   111,   111,   111,   111,   111,
   111,   111,   111,   111,   111,   111,   111,   111,   111,   111,
   111,   111,   111,   111,   111,   111,   111,   111,   111,   111,
   111,   111,   111,   111,   111,   111,   111,   111,   111,   111,
   112,   112,   112,   112,   112,   112,   nil,   112,   112,   nil,
   112,   112,   112,   112,   nil,   nil,   112,   112,   nil,   112,
   nil,   112,   112,   nil,   112,   112,   112,   112,   112,   112,
   112,   112,   112,   112,   112,   112,   112,   112,   112,   112,
   112,   112,   112,   112,   112,   112,   112,   112,   112,   112,
   112,   112,   112,   112,   112,   112,   112,   112,   112,   112,
   116,   116,   116,   116,   116,   116,   nil,   116,   116,   nil,
   116,   116,   116,   116,   nil,   nil,   116,   116,   116,   116,
   116,   116,   116,   116,   116,   116,   116,   116,   116,   116,
   116,   116,   116,   116,   116,   116,   116,   116,   116,   116,
   116,   116,   116,   116,   116,   116,   116,   116,   116,   116,
   116,   116,   116,   116,   116,   116,   116,   116,   116,   116,
   122,   122,   122,   122,   122,   122,   nil,   122,   122,   nil,
   122,   122,   122,   122,   nil,   nil,   122,   122,   nil,   122,
   nil,   122,   122,   nil,   nil,   122,   122,   122,   122,   122,
   122,   122,   122,   122,   122,   122,   122,   122,   122,   122,
   122,   122,   122,   122,   122,   122,   122,   122,   122,   122,
   122,   122,   122,   122,   122,   122,   122,   122,   122,   122,
   129,   129,   129,   129,   129,   129,   nil,   129,   129,   nil,
   129,   129,   129,   129,   nil,   nil,   129,   129,   nil,   129,
   nil,   129,   129,   nil,   129,   129,   129,   129,   129,   129,
   129,   129,   129,   129,   129,   129,   129,   129,   129,   129,
   129,   129,   129,   129,   129,   129,   129,   129,   129,   129,
   129,   129,   129,   129,   129,   129,   129,   129,   129,   129,
   155,   155,   nil,   nil,   nil,   155,   155,   155,   155,   nil,
   155,   155,   155,   155,   nil,   nil,   155,   155,   155,   155,
   155,   155,   155,   155,   155,   155,   155,   155,   155,   155,
   155,   155,   155,   155,   155,   155,   155,   155,   155,   155,
   155,   155,   155,   155,   155,   155,   155,   155,   155,   155,
   155,   155,   155,   155,   155,   155,   155,   155,   155,   155,
   156,   156,   nil,   nil,   nil,   156,   156,   156,   156,   nil,
   156,   156,   156,   156,   nil,   nil,   156,   156,   156,   156,
   156,   156,   156,   156,   156,   156,   156,   156,   156,   156,
   156,   156,   156,   156,   156,   156,   156,   156,   156,   156,
   156,   156,   156,   156,   156,   156,   156,   156,   156,   156,
   156,   156,   156,   156,   156,   156,   156,   156,   156,   156,
    12,    12,    12,    12,   nil,   nil,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12 ]

racc_action_pointer = [
    -2,     2,   -14,    58,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,  1008,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -11,   nil,   -12,    -1,     0,    47,
    51,    64,   nil,   nil,   nil,   118,    48,   178,   nil,   238,
   298,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   358,    63,   nil,   nil,   nil,    60,   nil,   104,   103,
   nil,   nil,   418,   nil,   nil,   nil,   nil,   nil,   nil,   478,
   538,   598,   658,   130,   131,   nil,   718,   175,   173,   172,
   169,   nil,   778,   172,   nil,   nil,   nil,   nil,   nil,   838,
   181,   182,   222,   218,   240,   244,   239,   250,   nil,   nil,
   nil,   nil,   287,   277,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   298,   898,   958,   303,   nil,   nil,
   nil,   nil,   nil,   nil ]

racc_action_default = [
  -125,  -125,  -125,    -2,    -4,    -5,    -6,    -7,    -8,    -9,
   -10,   -11,   -12,   -14,   -15,   -16,   -17,   -18,   -19,   -20,
   -21,   -22,   -23,   -24,   -25,   -26,   -27,   -28,   -29,   -30,
   -31,   -32,   -33,   -34,   -35,   -36,   -37,   -38,   -39,   -40,
   -41,   -42,   -43,   -44,   -45,   -46,   -47,   -48,   -49,   -50,
   -51,   -52,   -53,   -54,   -55,   -56,   -57,   -58,   -59,   -60,
   -61,   -62,   -63,   -64,  -125,   -73,   -89,  -125,  -125,  -125,
  -125,  -125,    -1,    -3,   -13,   -80,   -75,  -125,  -115,  -125,
  -125,  -124,   164,   -65,   -66,   -67,   -68,   -69,   -70,   -71,
   -72,   -80,   -83,   -86,   -87,   -88,  -125,   -90,  -125,   -93,
   -96,   -97,   -98,  -100,  -101,  -102,  -103,  -104,  -105,  -109,
  -109,  -109,  -109,  -116,  -116,   -81,   -80,   -83,  -125,  -125,
   -77,   -91,  -125,   -93,   -95,   -99,  -106,  -107,  -108,  -109,
  -125,  -125,  -125,  -125,  -116,  -118,  -125,  -118,   -82,   -84,
   -85,   -74,  -125,   -77,   -79,   -92,   -94,  -110,  -111,  -112,
  -113,  -114,  -117,  -119,  -125,  -125,  -125,  -125,   -76,   -78,
  -120,  -123,  -122,  -121 ]

racc_goto_table = [
     2,   104,    99,   100,   101,   105,   154,   118,   157,     1,
    73,    93,    74,    75,    90,    94,   119,    98,   124,   125,
   144,   nil,   nil,   135,   137,    92,   104,    93,   100,   101,
   105,    94,   139,   104,   104,   104,   104,   105,   105,   105,
   105,   115,   146,   159,   152,   nil,   104,   145,   100,   101,
   105,   nil,    93,   104,   nil,   nil,    94,   105,   130,   131,
   132,   133,   nil,   nil,   nil,   nil,   138,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   147,   113,
   114,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   161,   162 ]

racc_goto_check = [
     2,    14,    28,    31,    32,    15,    40,    26,    40,     1,
     4,    12,    13,    18,    19,    16,    20,    27,    30,    34,
    22,   nil,   nil,    39,    39,    24,    14,    12,    31,    32,
    15,    16,    26,    14,    14,    14,    14,    15,    15,    15,
    15,    24,    30,    22,    39,   nil,    14,    28,    31,    32,
    15,   nil,    12,    14,   nil,   nil,    16,    15,    36,    36,
    36,    36,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    36,     2,
     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     2,     2 ]

racc_goto_pointer = [
   nil,     9,     0,   nil,     7,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -64,     0,   -76,   -72,   -60,   nil,   -51,   -61,
   -80,   nil,  -100,   nil,   -50,   nil,   -85,   -60,   -75,   nil,
   -81,   -74,   -73,   nil,   -83,   nil,   -51,   nil,   nil,   -90,
  -129 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,   106,    64,   nil,   nil,
   nil,   143,   nil,    91,   nil,   117,   nil,   nil,   nil,   123,
   nil,   126,   127,   102,   103,   129,   nil,   134,   153,   nil,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 64, :_reduce_1,
  1, 67, :_reduce_2,
  2, 67, :_reduce_3,
  1, 65, :_reduce_4,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 76, :_reduce_12,
  2, 76, :_reduce_13,
  1, 68, :_reduce_14,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  3, 69, :_reduce_72,
  1, 80, :_reduce_73,
  4, 81, :_reduce_74,
  1, 81, :_reduce_75,
  2, 84, :_reduce_76,
  0, 85, :_reduce_77,
  2, 85, :_reduce_78,
  2, 83, :_reduce_79,
  0, 87, :_reduce_80,
  2, 87, :_reduce_81,
  2, 88, :_reduce_82,
  0, 89, :_reduce_83,
  2, 89, :_reduce_84,
  3, 82, :_reduce_85,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 70, :_reduce_89,
  3, 70, :_reduce_90,
  4, 70, :_reduce_91,
  2, 92, :_reduce_92,
  0, 93, :_reduce_93,
  2, 93, :_reduce_94,
  2, 90, :_reduce_95,
  1, 96, :_reduce_96,
  1, 96, :_reduce_97,
  1, 97, :_reduce_98,
  2, 97, :_reduce_99,
  1, 91, :_reduce_100,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 98, :_reduce_106,
  1, 98, :_reduce_107,
  1, 98, :_reduce_108,
  0, 99, :_reduce_109,
  2, 99, :_reduce_110,
  3, 95, :_reduce_111,
  3, 95, :_reduce_112,
  3, 95, :_reduce_113,
  3, 95, :_reduce_114,
  2, 71, :_reduce_115,
  0, 102, :_reduce_116,
  2, 102, :_reduce_117,
  0, 103, :_reduce_none,
  1, 103, :_reduce_none,
  6, 72, :_reduce_120,
  6, 73, :_reduce_121,
  3, 100, :_reduce_122,
  2, 101, :_reduce_123,
  2, 74, :_reduce_124 ]

racc_reduce_n = 125

racc_shift_n = 164

racc_token_table = {
  false => 0,
  :error => 1,
  :PP_IFDEF => 2,
  :PP_IFNDEF => 3,
  :PP_ELSIF => 4,
  :PP_ELSE => 5,
  :PP_ENDIF => 6,
  :PP_DEFINE => 7,
  :PP_UNDEF => 8,
  :PP_INCLUDE => 9,
  :PP_MACRO_ID => 10,
  :PP_NL => 11,
  :STRING => 12,
  :NUMBER => 13,
  :VERILOG_NUMBER => 14,
  :SIMPLE_ID => 15,
  :NL => 16,
  :EOS => 17,
  :ILLEGAL_CHARACTER => 18,
  "[" => 19,
  "]" => 20,
  "(" => 21,
  ")" => 22,
  "#(" => 23,
  "{" => 24,
  "}" => 25,
  "," => 26,
  "!" => 27,
  "&&" => 28,
  "||" => 29,
  "<" => 30,
  ">" => 31,
  "<=" => 32,
  ">=" => 33,
  "==" => 34,
  "!=" => 35,
  ">>" => 36,
  "<<" => 37,
  "~" => 38,
  "&" => 39,
  "~&" => 40,
  "|" => 41,
  "~|" => 42,
  "^" => 43,
  "~^" => 44,
  "^~" => 45,
  "*" => 46,
  "/" => 47,
  "%" => 48,
  "+" => 49,
  "-" => 50,
  "**" => 51,
  "?" => 52,
  ":" => 53,
  "->" => 54,
  "." => 55,
  "'" => 56,
  ";" => 57,
  "=" => 58,
  "@" => 59,
  "+=" => 60,
  "%=" => 61,
  "-temp-group" => 62 }

racc_nt_base = 63

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "PP_IFDEF",
  "PP_IFNDEF",
  "PP_ELSIF",
  "PP_ELSE",
  "PP_ENDIF",
  "PP_DEFINE",
  "PP_UNDEF",
  "PP_INCLUDE",
  "PP_MACRO_ID",
  "PP_NL",
  "STRING",
  "NUMBER",
  "VERILOG_NUMBER",
  "SIMPLE_ID",
  "NL",
  "EOS",
  "ILLEGAL_CHARACTER",
  "\"[\"",
  "\"]\"",
  "\"(\"",
  "\")\"",
  "\"#(\"",
  "\"{\"",
  "\"}\"",
  "\",\"",
  "\"!\"",
  "\"&&\"",
  "\"||\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"==\"",
  "\"!=\"",
  "\">>\"",
  "\"<<\"",
  "\"~\"",
  "\"&\"",
  "\"~&\"",
  "\"|\"",
  "\"~|\"",
  "\"^\"",
  "\"~^\"",
  "\"^~\"",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "\"**\"",
  "\"?\"",
  "\":\"",
  "\"->\"",
  "\".\"",
  "\"'\"",
  "\";\"",
  "\"=\"",
  "\"@\"",
  "\"+=\"",
  "\"%=\"",
  "\"-temp-group\"",
  "$start",
  "root",
  "source_description",
  "source_item",
  "\"-many1@source_item\"",
  "rdl_tokens",
  "text_macro_definition",
  "text_macro_usage",
  "undef",
  "ifdef",
  "ifndef",
  "include",
  "rdl_token",
  "\"-many1@rdl_token\"",
  "rdl_literal",
  "rdl_symbol",
  "pp_keyword",
  "text_macro_start",
  "text_macro_header",
  "text_macro_body",
  "text_macro_params",
  "\"-group@\\\",\\\"-SIMPLE_ID\"",
  "\"-many@-group@\\\",\\\"-SIMPLE_ID\"",
  "text_macro_token",
  "\"-many@text_macro_token\"",
  "\"-group@PP_NL-\\\"-many@text_macro_token\\\"\"",
  "\"-many@-group@PP_NL-\\\"-many@text_macro_token\\\"\"",
  "text_macro_args",
  "text_macro_arg",
  "\"-group@\\\",\\\"-text_macro_arg\"",
  "\"-many@-group@\\\",\\\"-text_macro_arg\"",
  "text_macro_simple_arg_element",
  "text_macro_bracketed_arg_group",
  "\"-group@text_macro_simple_arg_element|text_macro_bracketed_arg_group\"",
  "\"-many1@-group@text_macro_simple_arg_element|text_macro_bracketed_arg_group\"",
  "\"-group@text_macro_simple_arg_element|text_macro_bracketed_arg_group|\\\",\\\"\"",
  "\"-many@-group@text_macro_simple_arg_element|text_macro_bracketed_arg_group|\\\",\\\"\"",
  "elsif",
  "else",
  "\"-many@elsif\"",
  "\"-option@else\"" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'preprocessor.y', 20)
  def _reduce_1(val, _values, result)
            result = Root.new(val[0], val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 30)
  def _reduce_2(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 30)
  def _reduce_3(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 25)
  def _reduce_4(val, _values, result)
            result = SourceDescription.new(val[0])

    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'preprocessor.y', 43)
  def _reduce_12(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 43)
  def _reduce_13(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 39)
  def _reduce_14(val, _values, result)
            result = RdlTokens.new(val[0])

    result
  end
.,.,

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

module_eval(<<'.,.,', 'preprocessor.y', 60)
  def _reduce_72(val, _values, result)
            result = Define.new(val[1][0], val[1][1], val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 64)
  def _reduce_73(val, _values, result)
            enter_macro_body
        result = val[0]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 69)
  def _reduce_74(val, _values, result)
            result = [val[0], val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 72)
  def _reduce_75(val, _values, result)
            result = [val[0]]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_76(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_77(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_78(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 76)
  def _reduce_79(val, _values, result)
            result = collect_list_items(val)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_80(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_81(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_82(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_83(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 85)
  def _reduce_84(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 80)
  def _reduce_85(val, _values, result)
            exit_macro_body
        result = val.flatten

    result
  end
.,.,

# reduce 86 omitted

# reduce 87 omitted

# reduce 88 omitted

module_eval(<<'.,.,', 'preprocessor.y', 91)
  def _reduce_89(val, _values, result)
            token_range = Utils.to_token_range(val)
        result = MacroUsage.new(val[0], nil, nil, nil, token_range)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 95)
  def _reduce_90(val, _values, result)
            token_range = Utils.to_token_range(val)
        result = MacroUsage.new(val[0], nil, val[1], val[2], token_range)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 99)
  def _reduce_91(val, _values, result)
            token_range = Utils.to_token_range(val)
        result = MacroUsage.new(val[0], val[2], nil, nil, token_range)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 108)
  def _reduce_92(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 108)
  def _reduce_93(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 108)
  def _reduce_94(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 104)
  def _reduce_95(val, _values, result)
            result = collect_list_items(val)

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 112)
  def _reduce_96(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 112)
  def _reduce_97(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 112)
  def _reduce_98(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 112)
  def _reduce_99(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 108)
  def _reduce_100(val, _values, result)
            result = val[0].flatten

    result
  end
.,.,

# reduce 101 omitted

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

module_eval(<<'.,.,', 'preprocessor.y', 131)
  def _reduce_106(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 131)
  def _reduce_107(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 131)
  def _reduce_108(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 131)
  def _reduce_109(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 131)
  def _reduce_110(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 114)
  def _reduce_111(val, _values, result)
            result = val.flatten

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 117)
  def _reduce_112(val, _values, result)
            result = val.flatten

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 120)
  def _reduce_113(val, _values, result)
            result = val.flatten

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 123)
  def _reduce_114(val, _values, result)
            result = val.flatten

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 131)
  def _reduce_115(val, _values, result)
            result = Undef.new(val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 144)
  def _reduce_116(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 144)
  def _reduce_117(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 118 omitted

# reduce 119 omitted

module_eval(<<'.,.,', 'preprocessor.y', 139)
  def _reduce_120(val, _values, result)
            if_branch = [val[1], false, val[2]]
        result = Ifdef.new(if_branch, val[3], val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 144)
  def _reduce_121(val, _values, result)
          if_branch = [val[1], true, val[2]]
      result = Ifdef.new(if_branch, val[3], val[4])

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 149)
  def _reduce_122(val, _values, result)
            result = [val[1], false, val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 153)
  def _reduce_123(val, _values, result)
            result = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'preprocessor.y', 161)
  def _reduce_124(val, _values, result)
            result = Include.new(val[1])

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

      end   # class GeneratedPreprocessor
    end   # module Preprocessor
  end   # module Parser
end   # module SystemRDL
