# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "systemrdl.y".
#

require 'racc/parser.rb'
module SystemRDL
  module Parser
    class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     6,     7,     8 ]

racc_action_check = [
     0,     1,     7 ]

racc_action_pointer = [
    -2,     1,   nil,   nil,   nil,   nil,   nil,     2,   nil ]

racc_action_default = [
    -6,    -6,    -1,    -2,    -3,    -4,    -5,    -6,     9 ]

racc_goto_table = [
     1,     2,     3,     4,     5 ]

racc_goto_check = [
     1,     2,     3,     4,     5 ]

racc_goto_pointer = [
   nil,     0,     1,     2,     3,     4 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 4, :_reduce_none,
  1, 5, :_reduce_2,
  1, 6, :_reduce_none,
  1, 7, :_reduce_none,
  1, 8, :_reduce_5 ]

racc_reduce_n = 6

racc_shift_n = 9

racc_token_table = {
  false => 0,
  :error => 1,
  :BOOLEAN => 2 }

racc_nt_base = 3

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "BOOLEAN",
  "$start",
  "root",
  "test_expression",
  "expression",
  "primary_literal",
  "boolean_literal" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'systemrdl.y', 10)
  def _reduce_2(val, _values, result)
            if test?
          val[0]
        else
          # todo
        end

    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

module_eval(<<'.,.,', 'systemrdl.y', 24)
  def _reduce_5(val, _values, result)
            result = AST::Boolean.new(val[0])

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class GeneratedParser
  end   # module Parser
end   # module SystemRDL
