# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "systemrdl.y".
#

require 'racc/parser.rb'
module SystemRDL
  module Parser
    class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    38,    47,    48,    51,    54,    55,    46,    48,    18,    46,
    40,    41,    54,    61,   nil,   nil,   nil,    19,   nil,   nil,
    10,   nil,   nil,   nil,   nil,    22,    26,   nil,   nil,    39,
   nil,    27,    28,    20,    24,   nil,     9,   nil,    42,   nil,
    17,   nil,   nil,    23,    25,    35,    30,    29,    31,    21,
    36,    37,    33,    32,    34,    38,   nil,   nil,   nil,    11,
    46,   nil,   nil,    18,   nil,    40,    41,   nil,   nil,   nil,
   nil,   nil,    19,   nil,   nil,    10,   nil,   nil,   nil,   nil,
    22,    26,   nil,   nil,    39,   nil,    27,    28,    20,    24,
   nil,     9,   nil,    42,   nil,    17,   nil,   nil,    23,    25,
    35,    30,    29,    31,    21,    36,    37,    33,    32,    34,
   nil,   nil,   nil,   nil,    11,    46 ]

racc_action_check = [
     0,     1,     4,     5,     7,    47,    48,    49,     0,    51,
     0,     0,    52,    60,   nil,   nil,   nil,     0,   nil,   nil,
     0,   nil,   nil,   nil,   nil,     0,     0,   nil,   nil,     0,
   nil,     0,     0,     0,     0,   nil,     0,   nil,     0,   nil,
     0,   nil,   nil,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    54,   nil,   nil,   nil,     0,
     0,   nil,   nil,    54,   nil,    54,    54,   nil,   nil,   nil,
   nil,   nil,    54,   nil,   nil,    54,   nil,   nil,   nil,   nil,
    54,    54,   nil,   nil,    54,   nil,    54,    54,    54,    54,
   nil,    54,   nil,    54,   nil,    54,   nil,   nil,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
   nil,   nil,   nil,   nil,    54,    54 ]

racc_action_pointer = [
   -11,     1,   nil,   nil,   -67,   -65,   nil,   -62,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,   -65,   -62,
   nil,   -62,   -54,   nil,    44,   nil,   nil,   nil,   nil,   nil,
   -54,   nil ]

racc_action_default = [
   -53,   -53,    -1,    -2,    -4,    -9,    -8,   -10,   -14,   -15,
   -16,   -17,   -18,   -19,   -20,   -21,   -22,   -23,   -24,   -25,
   -26,   -27,   -28,   -29,   -30,   -31,   -32,   -33,   -34,   -35,
   -36,   -37,   -38,   -39,   -40,   -41,   -42,   -43,   -44,   -45,
   -46,   -47,   -48,   -49,   -50,   -51,   -52,   -53,   -53,    -4,
    -6,   -53,   -10,   -12,   -53,    62,    -3,    -5,    -7,   -11,
   -53,   -13 ]

racc_goto_table = [
     3,    50,    53,     1,     2,    56,    58,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    57,    59,   nil,   nil,
   nil,   nil,   nil,   nil,    60 ]

racc_goto_check = [
     3,     8,    12,     1,     2,     5,     9,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     8,    12,   nil,   nil,
   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,     3,     4,     0,   nil,   -43,   nil,   nil,    -3,   -45,
   nil,   nil,    -5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     5,     4,     6,    49,   nil,     7,
    45,    52,   nil,    44,     8,    12,    13,    14,    15,    16,
    43 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 74, :_reduce_none,
  1, 75, :_reduce_2,
  2, 80, :_reduce_3,
  0, 81, :_reduce_4,
  2, 81, :_reduce_5,
  2, 77, :_reduce_6,
  3, 79, :_reduce_7,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  0, 85, :_reduce_10,
  2, 85, :_reduce_11,
  2, 78, :_reduce_12,
  3, 84, :_reduce_13,
  1, 86, :_reduce_14,
  1, 86, :_reduce_15,
  1, 86, :_reduce_16,
  1, 86, :_reduce_17,
  1, 86, :_reduce_18,
  1, 86, :_reduce_19,
  1, 86, :_reduce_20,
  1, 86, :_reduce_21,
  1, 86, :_reduce_22,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 76, :_reduce_none,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 82, :_reduce_52 ]

racc_reduce_n = 53

racc_shift_n = 62

racc_token_table = {
  false => 0,
  :error => 1,
  :ABSTRACT => 2,
  :ACCESSTYPE => 3,
  :ADDRESSINGTYPE => 4,
  :ADDRMAP => 5,
  :ALIAS => 6,
  :ALL => 7,
  :BIT => 8,
  :BOOLEAN => 9,
  :BOTHEDGE => 10,
  :COMPACT => 11,
  :COMPONENT => 12,
  :COMPONENTWIDTH => 13,
  :CONSTRAINT => 14,
  :DEFAULT => 15,
  :ENCODE => 16,
  :ENUM => 17,
  :EXTERNAL => 18,
  :FALSE => 19,
  :FIELD => 20,
  :FULLALIGN => 21,
  :HW => 22,
  :INSIDE => 23,
  :INTERNAL => 24,
  :LEVEL => 25,
  :LONGINT => 26,
  :MEM => 27,
  :NA => 28,
  :NEGEDGE => 29,
  :NONSTICKY => 30,
  :NUMBER => 31,
  :ONREADTYPE => 32,
  :ONWRITETYPE => 33,
  :POSEDGE => 34,
  :PROPERTY => 35,
  :R => 36,
  :RCLR => 37,
  :REF => 38,
  :REG => 39,
  :REGALIGN => 40,
  :REGFILE => 41,
  :RSET => 42,
  :RUSER => 43,
  :RW => 44,
  :RW1 => 45,
  :SIGNAL => 46,
  :STRING => 47,
  :STRUCT => 48,
  :SW => 49,
  :THIS => 50,
  :TRUE => 51,
  :TYPE => 52,
  :UNSIGNED => 53,
  :W => 54,
  :W1 => 55,
  :WCLR => 56,
  :WOCLR => 57,
  :WOSET => 58,
  :WOT => 59,
  :WR => 60,
  :WSET => 61,
  :WUSER => 62,
  :WZC => 63,
  :WZS => 64,
  :WZT => 65,
  :L_BRACKET => 66,
  :R_BRACKET => 67,
  :ARROW => 68,
  :DOT => 69,
  :VERILOG_NUMBER => 70,
  :SIMPLE_ID => 71,
  "-temp-group" => 72 }

racc_nt_base = 73

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "ABSTRACT",
  "ACCESSTYPE",
  "ADDRESSINGTYPE",
  "ADDRMAP",
  "ALIAS",
  "ALL",
  "BIT",
  "BOOLEAN",
  "BOTHEDGE",
  "COMPACT",
  "COMPONENT",
  "COMPONENTWIDTH",
  "CONSTRAINT",
  "DEFAULT",
  "ENCODE",
  "ENUM",
  "EXTERNAL",
  "FALSE",
  "FIELD",
  "FULLALIGN",
  "HW",
  "INSIDE",
  "INTERNAL",
  "LEVEL",
  "LONGINT",
  "MEM",
  "NA",
  "NEGEDGE",
  "NONSTICKY",
  "NUMBER",
  "ONREADTYPE",
  "ONWRITETYPE",
  "POSEDGE",
  "PROPERTY",
  "R",
  "RCLR",
  "REF",
  "REG",
  "REGALIGN",
  "REGFILE",
  "RSET",
  "RUSER",
  "RW",
  "RW1",
  "SIGNAL",
  "STRING",
  "STRUCT",
  "SW",
  "THIS",
  "TRUE",
  "TYPE",
  "UNSIGNED",
  "W",
  "W1",
  "WCLR",
  "WOCLR",
  "WOSET",
  "WOT",
  "WR",
  "WSET",
  "WUSER",
  "WZC",
  "WZS",
  "WZT",
  "L_BRACKET",
  "R_BRACKET",
  "ARROW",
  "DOT",
  "VERILOG_NUMBER",
  "SIMPLE_ID",
  "\"-temp-group\"",
  "$start",
  "root",
  "test_expression",
  "constant_expression",
  "instance_ref",
  "instance_ref_element",
  "prop_ref",
  "\"-group@DOT-instance_ref_element\"",
  "\"-many@-group@DOT-instance_ref_element\"",
  "id",
  "instance_or_prop_ref",
  "array",
  "\"-many@array\"",
  "primary_literal",
  "boolean_literal",
  "accesstype_literal",
  "onreadtype_literal",
  "onwritetype_literal",
  "addressingtype_literal",
  "precedencetype_literal",
  "constant_primary" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'systemrdl.y', 31)
  def _reduce_2(val, _values, result)
            unless test?
          # todo
          # report parse error
        end

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 48)
  def _reduce_3(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 48)
  def _reduce_4(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 48)
  def _reduce_5(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 42)
  def _reduce_6(val, _values, result)
            val = to_list(val, include_separator: true)
        range = to_token_range(val)
        result = AST::InstanceRef.new(range, *val)

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 48)
  def _reduce_7(val, _values, result)
            range = to_token_range(val)
        result = AST::PropRef.new(range, val[0], val[2])

    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

module_eval(<<'.,.,', 'systemrdl.y', 66)
  def _reduce_10(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 66)
  def _reduce_11(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 56)
  def _reduce_12(val, _values, result)
          val = to_list(val, include_separator: false)
      range = to_token_range(val)
      result = AST::InstanceRefElement.new(range, val[0], *val[1..])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 66)
  def _reduce_13(val, _values, result)
            range = to_token_range(val)
        result = AST::Array.new(range, val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 75)
  def _reduce_14(val, _values, result)
            range = to_token_range(val[0])
        result = AST::Boolean.new(range, val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 79)
  def _reduce_15(val, _values, result)
            range = to_token_range(val[0])
        result = AST::String.new(range, val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 83)
  def _reduce_16(val, _values, result)
            range = to_token_range(val[0])
        result = AST::Number.new(range, val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 87)
  def _reduce_17(val, _values, result)
            range = to_token_range(val[0])
        result = AST::VerilogNumber.new(range, val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 91)
  def _reduce_18(val, _values, result)
            range = to_token_range(val[0])
        result = AST::AccessType.new(range, val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 95)
  def _reduce_19(val, _values, result)
            range = to_token_range(val[0])
        result = AST::OnReadType.new(range, val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 99)
  def _reduce_20(val, _values, result)
            range = to_token_range(val[0])
        result = AST::OnWriteType.new(range, val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 103)
  def _reduce_21(val, _values, result)
            range = to_token_range(val[0])
        result = AST::AddressingType.new(range, val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'systemrdl.y', 107)
  def _reduce_22(val, _values, result)
            range = to_token_range(val[0])
        result = AST::PrecedenceType.new(range, val[0])


    result
  end
.,.,

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

module_eval(<<'.,.,', 'systemrdl.y', 138)
  def _reduce_52(val, _values, result)
            range = to_token_range(val[0])
        result = AST::ID.new(range, val[0])

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class GeneratedParser
  end   # module Parser
end   # module SystemRDL
