name: Unit Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.1'
          - '3.0'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run RSec
      run: bundle exec rake coverage

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        name: ruby-${{ matrix.ruby }}
        file: ./coverage/coverage.xml
